### ISSUE TITLE
domain and sub domain

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#10]
Hi, I have problem with domain and subdomain,
the principal domain is -> www.myapp.com AND subdomain is -> sub.myapp.com and getting in controller the SERVER NAME to pass as variable to render the view. 

If I type in browser www.myapp.com/mypage or sub.myapp.com/mypage work but any link in template (app.url()) or in code $app->redirect() get the principal domain.

Where I am in wrong ?

Thanks.

**Comment by ocram** [comment]
The configuration contains a property named [`APP_PUBLIC_URL`](https://github.com/delight-im/PHP-Foundation/blob/7fcf923065eab634dae2cf04b4c330494a81e33b/config/.env.example#L6) which defines your application’s base URL. You probably have configured this at the beginning.

This is what controls the URLs that are generated by `App#url` and `App#redirect`.

It seems that what you want is to have the possibility to define *multiple* URLs in the configuration so that the framework picks up whichever URL is currently used. Is that correct?

For example, you may have defined `https://www.example.com/` and `http://sub.example.com` in the configuration. Then:

 * If the user visits via `https://www.example.com/hello.html`, this will work and pick up the first URL from the configuration.
 * If the user visits via `http://sub.example.com/world.html`, this will work and pick up the second URL from the configuration.
 * If the user visits via `http://some.test/index.html`, it will *not* work.

Is this what you want?

**Comment by daebak74** [comment]
Yes! But for me doesn't work sub.example.com/world.html work only if I type in the browser but all the link with app get the domain in config file. (Of coarse). Maybe in config need to add the subdomain too an how? Or bypass it ? Anyway if you can are the server name origin could be perfect.

Thanks.

**Comment by ocram** [comment]
That’s what I said: Right now, the output of `App#url` and `App#redirect` only uses the configured base URL and thus only supports *one* hostname. What you are requesting is apparently that this is extended so that you can define *multiple* hostnames, right?

The reason this is not implemented already is that you usually don’t want that. Multiple hostnames pointing to the same application does not give you any advantages but results in duplicate content if you build an application with (text) content and care about SEO.

Instead, most often you’ll want to *redirect* the other hostnames to the preferred hostname with a `301` HTTP status.

**Comment by daebak74** [comment]
Why duplicated content or seo penalty. Most of the framework use multiple root. As e-commerce with multiple storefront,  classified, travel portal. spain.mydream.com france.mydrean.com/hotel. Sitemap generated dynamically I don't see penalty . Anyway got your point the framework get the url from config file so one domain.
Thanks.

**Comment by ocram** [comment]
I was only talking about actually duplicate content, e.g. the bare domain and the `www` subdomain pointing to the same application directory, or the `.com` domain and the `.co.uk` domain.

But if you actually check the subdomain that has been used and generate different content based on that subdomain, you don’t have any duplicate content.

So your use cases of using separate subdomains for individual store fronts, or one subdomain per country or language, are excellent examples. Good point!

We must definitely implement that. Let’s keep this issue here open again to track our progress until it’s implemented.

**Comment by ocram** [comment]
This has been implemented [here](https://github.com/delight-im/PHP-Foundation-Core/commit/0f48596a4f6b40fcddec0e9d1a6a35f9a237fa81). Please use `composer update delight-im/foundation-core` to update this framework to `v4.2.0` and you’ll be able to add multiple supported URLs to `APP_PUBLIC_URL` in your configuration by separating them with a pipe or vertical bar character (`|`).

For your suggested use case, that should be something like this:

```
APP_PUBLIC_URL=http://www.myapp.com/|http://sub.myapp.com/
```
