### ISSUE TITLE
Auth registerWithUniqueUsername username shouldn't be optional

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#12]
It's not so important but If we set register with unique username the username shouldn't be optional but generate an exception with "invalid username" or is nonsense to select this option and have in db users with null username.
 
I wanna use username with unique rather than email because I consider more strong. I fix to return an error if username is null or client side as required so don't continue with the submit.
I report to you but maybe it is a desired choice.

Thanks.

**Comment by ocram** [comment]
Thanks!

Not totally sure about this. Your point makes sense, of course. But in the current form, it should allow for both a unique username or `null` (i.e. an empty username should always be valid).

That was desired behavior, because some may just want to prevent duplicate usernames, which you don’t have if a user chooses not to have a username at all.

If you don’t want to allow that, you can simply wrap a check like `!empty($username)` around the registration, which is a quick fix of two lines.

On the other hand, we can easily change the behavior in the authentication component as well, probably with three lines. And if we don’t do this, we should perhaps document this in the README.

By the way, it’s probably better if you submit issues for specific components that have their own repository (like the authentication component) in that specific repository.

**Comment by daebak74** [comment]
Yes what I am using in my case !empty($username) or return an error. You are right too if wanna use username but not required field become a reverse problem. 

So not need to open in Auth but I think you can close. :)
 
PS. I'll keep in mind to post in relative repository my posts. 

Thank you again for your fast feedback.

**Comment by ocram** [comment]
Sounds good. We’ll leave the current behavior for now, and will revisit this issue later if we change our minds and want to *require* usernames when they’re supposed to be unique. Thank you!
