### ISSUE TITLE
WampServer with vhost problem with APP_PUBLIC_URL

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#2]
Seems really a great base for speed web app development but I can't figure out how to configure the env for let work with my vhost

APP_PUBLIC_URL: http://localhost/ezsystem -> WORK GOOD
APP_PUBLIC_URL: http://ezsystem.servehttp.com -> PAGE NOT FOUND

this is my vost conf

<VirtualHost *:80>
    ServerAdmin emailaddress@domain.com
    DocumentRoot z:/ws/www/ezsystem
    ServerName ezsystem.servehttp.com
    ServerAlias ezsystem.servehttp.com
	ErrorLog "logs/ezsystem.log"
	CustomLog "logs/ezsystem-access.log" common
    <Directory "z:/ws/www/ezsystem">
		AllowOverride All
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		Order allow,deny
		Allow from all
    </Directory>
</VirtualHost>

Thank you for share and for support.

**Comment by ocram** [comment]
Thanks for your feedback!

Did you actually modify the `config/.env` file on your server (in that correct directory) or did you inadvertently modify it on your development machine?

It should definitely work with Apache and its Vhosts, though we have seen more deployments on Linux than on Windows, so perhaps that’s the cause for this issue. Anyway, it should be something that can be fixed.

By the way, is your development machine (`localhost`) on Windows as well?

What you should do first, please, is creating a simple `index.php` that prints some message and placing it in your Vhost directory (instead of this framework). If you open your designated URL and the message does not show up, we do at least know that the problem is somewhere else.

**Comment by daebak74** [comment]
Hallo @ocram Thanks for your fast reply. I wrote on the title and not in the post. I am in local pc with windows 10 and WampServer. the vhost work correctly is not the first project. I am testing your PHP Auth to in other folder and work perfect. I try to make simple the scenario.

- the forlder is z:\ws\www\ezsystem -> HERE YOUR PACKAGE
- z:\ws\www\ezsystem\config\.env -> YOUR CONFIG FILE
- this is my virtual host

<VirtualHost *:80>
	ServerAdmin emailaddress@domain.com
    DocumentRoot z:/ws/www/ezsystem
    ServerName ezsystem.servehttp.com
    ServerAlias ezsystem.servehttp.com
	ErrorLog "logs/ezsystem.log"
	CustomLog "logs/ezsystem-access.log" common
    <Directory "z:/ws/www/ezsystem">
		AllowOverride All
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		Order allow,deny
		Allow from all
    </Directory>
</VirtualHost>

- this in .env -> APP_PUBLIC_URL=http://ezsystem.servehttp.com
 
I can access to any php file with http://ezsystem.servehttp.com/test.php but if I try to access http://ezsystem.servehttp.com/ as the command in htaccess load the index.php in app but don't get the template and return the 404status 

// return an error page for undefined pages
$app->setStatus(404);
echo $app->view('404.html.twig');

if I set in .env -> APP_PUBLIC_URL=http://localhost/ezsystem

and type in the browser http://localhost/ezsystem everything work good and take the samples template welcome Alice .... 

There is some problem with route I think.

**Comment by daebak74** [comment]
Ok I after that I make different test maybe I had some cash problem I tried to clean the browser cache and now work the vhost too. 👍  Sorry for the issue and the time if I tried before I didn't let you waste your time.

**Comment by ocram** [comment]
No problem, glad you could resolve this. Thanks for sharing the solution!
