### ISSUE TITLE
wamp server refresh and replace cached and create po file

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#20]
In wamp server I have problem to exec shell command there is a solution for refresh and replace cached version of template and create PO file by php ?

welcome any other suggestions. 

Thank you!

EDIT:
I saw that are 2 functions in index.php so I exec from prompt

php ./index.php clear-template-cache -> OK
php ./index.php precompile-templates -> ERROR

Delight\Foundation\Throwable\TemplateNotFoundError: Unable to find template "Z:/ws/www/foundation/views/dashboard.html.twig" (looked into: Z:\ws\www\foundation/views). in file Z:\ws\www\foundation\vendor\delight-im\foundation-core\src\TemplateManager.php on line 162
Stack trace:
  1. Delight\Foundation\Throwable\TemplateNotFoundError->() Z:\ws\www\foundation\vendor\delight-im\foundation-core\src\TemplateManager.php:162
  2. Delight\Foundation\TemplateManager->precompile() Z:\ws\www\foundation\vendor\delight-im\foundation-core\src\App.php:931
  3. Delight\Foundation\App->precompileTemplates() Z:\ws\www\foundation\index.php:111

**Comment by ocram** [comment]
Thank you for your feedback on this!

The two commands that you tried will refresh the template cache for you, which is needed for all translations to be correctly extracted from the templates. But the commands will *not* perform the actual extraction. For this, you need a third command, which is `./i18n.sh` and will not work on Windows. But you could perhaps use WSL on Windows, or run the underlying commands yourself, which isn’t too hard. Just look inside `i18n.sh` to see which Gettext tools it calls.

Now concerning the error you described, `TemplateNotFoundError`, this is caused [here](https://github.com/delight-im/PHP-Foundation-Core/blob/c3161ae12de987e8d3ed2c818086df0ac0268567/src/TemplateManager.php#L159). Could you open `vendor/delight-im/foundation-core/src/TemplateManager.php` in your local application and try to debug this in order to see why it happens. It would be great if you could check which template it tries to load and why that fails, i.e. whether it’s actually missing or just cannot be found due to a wrongly specified path. Perhaps `realpath` must be called on the path before trying to load the template.

**Comment by daebak74** [comment]
Thanks. For the extraction I try to find some solution as you suggested. About the error I try to debug as soon as I come back. Just because there were different template and I suppose a wrong path I tried to make a test.  I empty the folder view and just put 1 template dashboard.html.twig and run the php command by windows prompt but nothing always the same error.

>  Perhaps realpath must be called on the path before trying to load the template.

Where I should use realpath ?

My files are

- routes

`$app->get('/admin/dashboard', ['\App\Controllers\Backend\Core\Dashboard', 'getDashboard']);`

- class

```
namespace App\Controllers\Backend\Core;
	
	use Delight\Foundation\App;
	
	class Dashboard {
		public static function getDashboard(App $app) {
			echo $app->view('/backend/'. $_SESSION['BE_THEME'] .'/core/dashboard.html.twig', [				
				'be_page_identifier' => 'dashboard', 
				'be_page_ref' => 'core', 
				'be_page_do' => 'dashboard'
			]);		
		}	
	}
```

BE_THEME is just for change template in this caxse is "default"

and in folder I put only this template

view/backend/default/core/dashboard.html.twig

Anyway I'll try to debug the template and I'll let you know.

**Comment by daebak74** [comment]
Ok I tried to print the $templateName in foreach and this is the result: 

Z:\ws\www\foundation/views\backend\default\core\dashboard.html.twig

problem with \  /  ?

**Comment by ocram** [comment]
Thanks!

You would need to open `vendor/delight-im/foundation-core/src/TemplateManager.php` and insert some debugging statements before (or around) [this exact line](https://github.com/delight-im/PHP-Foundation-Core/blob/c3161ae12de987e8d3ed2c818086df0ac0268567/src/TemplateManager.php#L159).

For example, what you could try *temporarily* is

```php
$templateName = \realpath($templateName);
```

or

```php
$templateName = \str_replace('Z:\\ws\\www\\foundation/views\\', '', $templateName);
```

or even

```php
$templateName = 'backend/default/core/dashboard.html.twig';
```

**Comment by daebak74** [comment]
`$templateName = \realpath($templateName);`

same error

`$templateName = \str_replace('Z:\\ws\\www\\foundation/views\\', '', $templateName);`

Work.

I fix in this way when I work in local ?

IF YES now show me other error 

TemplateSyntaxError: Unknown "ifFileExist" filter.

ifFileExist is a callback function that I use in template for check if file exist or use fallback file

```
{% set select2_lang = '/assets/select2/js/i18n/'~ session.EZ_LANG ~'.js' %}

{% if select2_lang | ifFileExist %}
<script src="{{ app.url('/assets/select2/js/i18n/'~ session.EZ_LANG ~'.js') }}"></script>
{% else %}
<script src="{{ app.url('/assets/select2/js/i18n/'~ session.EZ_FALLBACK_LANG ~'.js') }}"></script>
{% endif %}
```

**Comment by ocram** [comment]
Thanks a lot for testing these two changes and confirming that the `str_replace` solution works.

The reason was indeed that the template paths were not shortened from absolute paths to relative paths on Windows (due to the backslashes in the paths, which were not handled correctly).

This bug should have been fixed [in this commit](https://github.com/delight-im/PHP-Foundation-Core/commit/6e0cbd4f6629d0546f7bc9ddb790cc34b22f2b21) now.

Can you try running

```bash
$ composer update delight-im/foundation-core
```

to update it to `v4.10.1` (or later) and seeing if this solves the issue for you? Thanks!

Your second problem is best discussed in a separate issue, but generally, it means that `ifFileExist` has not been defined via

```php
$app->getTemplateManager()->addFilter('ifFileExist', function ($filename) {
    // TODO
    // return ...
});
```

**Comment by daebak74** [comment]
Yes the bug is fixed. About the second issue yes is definied 

```
$app->getTemplateManager()->addFilter('ifFileExist', function($file) {
 ...
});
```

I try to make some debug if I don't fix I'll open a different issue.

As always you are fast and kindly to offer your professional support.

Thank you very much!

**Comment by ocram** [comment]
Thanks for confirming the fix!

Let’s discuss your filter in the other issue.
