### ISSUE TITLE
Extend page view template

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#24]
I need help and try to simplify the problem. I'm doing a small version of cms to manage some sections of my frontend part application.

The pages are saved in the db and through a unique alias are recalled in the following way

`$app->get('/:alias', ['\App\Controllers\Pages', 'getPage']);`

and the controller is

```
class Pages {
	public static function getPage(App $app, $alias = null) {
        echo $app->view('/frontend/page.html.twig', [
	....
	]);
}
```

page.html.twig has the classic structure

```
<html>
<head></head>
<body>
{% block content %}{% endblock %}
</body>
</html>	
```	

Ok everything work good. Now start my problem

Each page has contents that are connected with the page by id

MYSQL

TABLE PAGES :: ID -> 1 - ALIAS -> alias
TABLE CONTENTS :: ID -> 1 - PAGE -> 1 - TEMPLATE -> content.html.twig

The result I would like to achieve is to dynamically include contents template from the controller in page view (page.html.twig)

My Idea is to use a select in controller on Table Contents by id and pass the template as extend

for example

content.html.twig is

```
{% extends '/frontend/page.html.twig' %}

{% block content %}
	{{ parent() }}
	.. my code ..
{% endblock %}
```

But this is wrong because the view template should be the content.html.twig and not page.html.twig

Hope to receive a valid and elegant solution :)

Thanks

**Comment by daebak74** [comment]
Change the name of page.html.twig to layout.html.twig create a new file with page.html.twig with this code:

`{% extends  'frontend/layout.html.twig' %}`

**Comment by ocram** [comment]
Sorry for the long delay!

Did you solve it by extending from the new `layout.html.twig`?

Otherwise, wouldn’t something like this have worked?

```php
public static function getPage(App $app, $alias = null) {
    $template = $app->db()->selectValue(
        "SELECT template FROM pages AS p JOIN contents AS c ON c.page = p.id WHERE p.alias = ?",
        [ $alias ]
    );

    if (!empty($template)) {
        echo $app->view($template);
    }
    else {
        echo $app->view('/frontend/page.html.twig');
    }
}
```

By the way, if you let the user choose paths at the root of your site, you always have to be careful, of course. You don’t want any user to choose `robots.txt`, for example. But if only the administrator has access, that might not even be a problem.

Finally, for untrusted content in templates, you may be interested in Twig’s sandbox:

 * https://twig.symfony.com/doc/1.x/tags/sandbox.html
 * https://twig.symfony.com/doc/1.x/api.html#sandbox-extension

**Comment by daebak74** [comment]
Even if in delay your answer are always very welcome. :) Anyway select the template for each alias would be a solution but my structure is different layout, module, contents,  articles, elements are created from be and stored in db so I think is better to render the view to a dynamic page.

I don't understand what do you mean can you explain with an example ?

> By the way, if you let the user choose paths at the root of your site, you always have to be careful, of course. You don’t want any user to choose robots.txt

Working with your framework I start to learn TWIG so not so familiar yet. Sandbox is for include templates and restrict the value available in that template ? I am using macro with custom filter for pass only the value available for that template.

Thanks.

**Comment by ocram** [comment]
> I don't understand what do you mean can you explain with an example ?

So you’re building a CMS, right? If you let your users choose paths at the root of your domain for their content, they could choose “/robots.txt” for a post or something like “/contact” that you’d like to use for other things, etc. So you may not want to allow for that. You could either prevent this by having a common prefix for all user-generated content, e.g. “/page/...”, or by creating a blacklist of paths or names that cannot be used.

> Sandbox is for include templates and restrict the value available in that template ?

You can read about Twig’s sandbox feature in their official documentation. It’s basically so that you can allow untrusted users to write pages in Twig. For example, when building a CMS, you may want to allow for any employee of a company, e.g. their web designer or an editor, to modify parts of their site that are written in Twig. In your example, you said you wanted to allow for dynamic templates stored in the database. If those templates can contain Twig code, you may want to improve security by not allowing every single of Twig to be used in there.
