### ISSUE TITLE
Render images stored in storage subfolder in protected area.

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#25]
In storage subfolder are stored user's private images. With an Ajax call I get a json and created the list but I can't render the image in html. How I can do it ?

Thanks.

**Comment by ocram** [comment]
You can make them available using [`App#serveFile`](https://github.com/delight-im/PHP-Foundation#serving-files), which should be what you want.

You would typically use this in a route like this:

```php
$app->get('/users/photos/:key', function ($key) {
    // ...
});
```

Of course, you usually need to check whether the client is actually allowed to view that photo, e.g. by checking in your database.

In your HTML source, you would then use image paths like `/users/photos/8723879234`.

Hope that helps!

**Comment by daebak74** [comment]
Thanks. But I need to pass the mime too or not need ? if required so 

```
$app->get('/users/photos/:mime/:key', function ($mime, $key) {
    // ...
});
```

`/users/photos/image-png/8723879234` and replace '-' with '/' ?

Curiosity... why use a key or is just and example because I am using normal file name myfile.png it's wrong ?

**Comment by ocram** [comment]
First, if you use a key or ID like `8723879234` and then look up the file in your database or on your file system, you usually don’t need to supply the MIME type because you can simply detect it from the file on the server. But of course you *could* provide the MIME type as an argument if you wanted. By the way, you probably don’t want users to be able to pick arbitrary MIME types to serve your content with.

Second, instead of a key as shown above, you can certainly send a file name like `myfile.png` directly in your parameters. In this case, where it would be a flat structure or a single folder, that could be fine. But you may not want to expose your whole internal file structure to the public. So perhaps you don’t want something like this:

```
/users/photos/%2Fapp%2Fstorage%2Fusers%2Fphotos%2Fprofile%2Fprocessed%2Fcompressed%2F42.jpg
```

That’s what the key or ID tried to avoid.

**Comment by daebak74** [comment]
Yes the file are served by internal file system but the admin have only access to a specific folder where organize subfolders and files

`storage/app/folder`

by a module that he can decide if render restricted for a group of users or not he can offer public or protected files stored in DB in JSON format 

`{'mime':'image/png', 'path': storage/app/folder/myimg.png}`

When the module is rendered in frontend area the files with origin `storage/app/folder` are already processed server side in served format

`/photo/image-png/myimg.png`

Yes. the subfolders from his folder are intuitable from the url.

I should to use KEY ? Any suggestions how to organize it ?

Thanks.

**Comment by ocram** [comment]
Well, let’s just use a short example.

In my file system, I have a user’s file that is stored at the following location:

```
/storage/app/users/28926491/photos/profile/92349.jpg
```

This is a private file, not accessible to the public because it’s neither in the `public` folder nor available via any route.

So we define a route that controls access to such private files:

```php
$app->get('/images/:which', function ($which) {
    // ...
}
```

Now you can either make the paths

```
/images/%2Fstorage%2Fapp%2Fusers%2F28926491%2Fphotos%2Fprofile%2F92349.jpg
```

by using the actual file path in the URL, or

```
/images/1027630194
```

by putting only an ID in the URL and then looking up which file that is when the request is handled, for example by searching in your database where you previously stored that mapping.

**Comment by daebak74** [comment]
The point of Key now is clear you mean the unique ID from DB but this means that all the files served have to be stored in it and I prefered the paths. But I have a problem because if I send the url as your example:

```
$app->get('/images/:path', function ($path) {
    // ...
}
```
`/images/%2Fstorage%2Fapp%2Fusers%2F28926491%2Fphotos%2Fprofile%2F92349.jpg`

Show me "page not found" because of coarse %2F is / where I am in wrong ?

Thanks

**Comment by ocram** [comment]
Can you print or `var_dump` the actual content of the `$path` variable? Is it the string you provided? Does it still have the escape characters? You could use `urldecode` then.

**Comment by daebak74** [comment]
I can't make any var_dump 
Yes I pass with urlencode but convert %2F in / so don't find the route.

```
$app->get('/images/:path', function ($path) {
    // ...
}
```

if I write on the browser www.mydomain.com/images%2Fphotos%2Fprofile%2F92349.jpg

The requested URL /images/photos/profile/92349.jpg was not found on this server.

**Comment by daebak74** [comment]
I got 

/images/test?f=myfirst/second/up/file.jpg

where test is the route and with u pass the path for use in serveFile
