### ISSUE TITLE
The real world with this package.

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#3]
I think this repository is one of the few, if not the only one, that offers an excellent startup for the development of applications leaving the freedom of customization. Thank you!

Many have asked you examples, (most for Auth) and how correct you answered the few important functions are present in the file. But I think an example or guidelines could be useful.

Personally I consider your work a great help because I come from development of applications always dependent on framework, so follow imposed roles and wanting to experiment with my own independent project I could run into organizational errors.

Below I try to list my scenario to respect and develop in logic with the system. (I would like to receive the BEST PRACTICE accoding your opinion)

BUILD AND APPLICATION BE/FE

1 - USERS AND RULES

Auth is complete with both the authentication process and rules. In a BE / FE system users (BE) and users (FE) are in separate tables. is it correct to use some Auth rules for user management (FE) or to consider a separate control system?

2 - THEMES AND TEMPLATE ENGINE (TWIG) 

Use TWIG to manage FE / BE templates, then organize the themes in the folder view with folder / subfolder?

Ex. views/
    - admin/
    -- default/
    - frontend/
    -- theme1/
    -- theme2/

3 - ROUTE

app/index.php is te main entry point here manage the request for BE/FE for example 

I just simplified the concept but need to use TWIG for manage THEME/LAYOUT/.....

$app->get('/', function (\Delight\Foundation\App $app) {
	// FE 
// do something with the FE structure n DB // 
// and return a view
	echo $app->view('THEME/welcome.html.twig', [
 'users' => [ 'Alice', 'Bob' ]
	]);

});

$app->get('/admin', function (\Delight\Foundation\App $app) {
	// BE 
// do something
	with the BE and include all the logic for BE APP // 
// and return a view
	echo $app->view('THEME/welcome.html.twig');

});

IT'S CORRECT ?

4 - LANGUAGE

What is your favorite solution for manage the multilanguage FE/BE?

I saw a package (PHPI18N) but of 5 years ago... is still the solution that you prefered agaist php array or other ?

Thanks for your support!

**Comment by ocram** [comment]
Thank you!

These are excellent questions.

> Auth is complete with both the authentication process and rules. In a BE / FE system users (BE) and users (FE) are in separate tables. is it correct to use some Auth rules for user management (FE) or to consider a separate control system?

You could either put all users (backend and frontend) into the same database tables and offer the same frontend (e.g. login, password reset) for both, while distinguishing between the two by using different [roles](https://github.com/delight-im/PHP-Auth#roles-or-groups) or [status flags](https://github.com/delight-im/PHP-Auth#status-information). By the way, you could disable password resets for the admin users.

Or you could create two different database schemas for the backend and the frontend, i.e. two sets of tables, where you would need an implementation in application code for both sets.

Both approaches are fine, and you’d need to choose what better fits your requirements.

> Use TWIG to manage FE / BE templates, then organize the themes in the folder view with folder / subfolder?

Yes, that’s what I would do.

> app/index.php is te main entry point here manage the request for BE/FE for example

Yes, that’s correct. There are several things you can do to simplify the code in `index.php` a lot:

 * Import the `App` class with a `use Delight\Foundation\App;` clause so that you only have to write `App` from then on, instead of the full `\Delight\Foundation\App`. See the [updated example](https://github.com/delight-im/PHP-Foundation/blob/487a8f1692421333b7adb45fd78d428b507f33ba/app/index.php).
 * Instead of using closures (anonymous functions), delegate the handling of the route to an external function or method: Just use `'SomeClass::someStaticMethod'` instead of the closure and move the implementation of the closure to that static method in your class. See the [updated example](https://github.com/delight-im/PHP-Foundation/blob/9f6c3183b04bc035fb443cb1896ee92345aa4ab2/app/index.php) and the [new controller classes](https://github.com/delight-im/PHP-Foundation/tree/9f6c3183b04bc035fb443cb1896ee92345aa4ab2/app).
 * You may split up your route definitions into two files, one handling the backend routes and one handling the frontend routes, e.g. `routes_backend.php` and `routes_frontend.php`, and then `require` both in `index.php`.

> What is your favorite solution for manage the multilanguage FE/BE?

We’re already working on a new I18N implementation. The old one has not been optimized to work with this framework here, but it was just used to set up and kick-start [Gettext](http://php.net/manual/en/book.gettext.php), which is still what we would recommend over arrays for translations.

**Comment by daebak74** [comment]
Thanks most of points are clear I asked because most of my app is ready need to migrate in mysqli to pdo but with pleasure because I like your clean solution of login and rules. I didn't think to change the ID it's correct and and can clean most of the code. 

- Use same table is the first idea that I think after checked your framework. And after your reply I think Less table and NOT duplicated code for check. For example if I use 

function feMember(\Delight\Auth\Auth $auth) {
    return $auth->hasAnyRole(
         \Delight\Auth\Role::CUSTOMER,
        \Delight\Auth\Role::MODERATOR,
        \Delight\Auth\Role::SUPER_MODERATOR,
        \Delight\Auth\Role::ADMIN,
        \Delight\Auth\Role::SUPER_ADMIN
    );
}

Than I need some other CHECK for restrict the access in FE AREA.... GROUPS as the most CMS ? 

- Disable password reset for BE user this is SURE but how can make this only for them ?

- said "using roles OR differet status flag" with status flag something I have in mind... but I prefer to listen from you :) What do you mean for differenciate BE/FE with different status Flag ?

> You may split up your route definitions into two files, one handling the backend routes and one handling the frontend routes, e.g. routes_backend.php and routes_frontend.php, and then require both in index.php

do you mean in app/index.php make something like this

request from FE include routes_frontend.phpand request from BE routes_backend.php if yes what I am thinking to do is ?

$app->get('/admin/', function (\Delight\Foundation\App $app) { // BE
	
	define('SYSTEM_MODE', 'BE');
	
	// do something
	
	// and return a view
	echo $app->view('admin/default/greeting.html.twig', []); --> SPLIT THEME
	
});

$app->get('/', function (\Delight\Foundation\App $app) { // FE

	define('SYSTEM_MODE', 'FE');
	
	// do something
	// ...

	// and return a view
	echo $app->view('frontend/default/welcome.html.twig', []); --> SPLIT THEME
	
});

- THEME USE FOLDER/SUBFOLDER
Ok seems that is the right direction... for better manage backup, import and so on the better way should be include directly in the folder of the theme the css and js over than layout and template..

views/
- frontend/
-- defaultheme/
--- css/
--- js/
..........
-- othertheme/

- LANGUAGE

Great to listen that you are rebuild I18N there is already some repositories that is possible to check or I can use it and update later ?

Thanks

**Comment by ocram** [comment]
> Than I need some other CHECK for restrict the access in FE AREA.... GROUPS as the most CMS ?

If your `feMember` function is meant to be interpreted as `isFeMember`, as opposed to `isBeMember`, it would make sense to exclude certain admin roles, wouldn’t it? You could say that users with the `\Delight\Auth\Role::SUPER_ADMIN` role have access to the backend, for example.

> Disable password reset for BE user this is SURE but how can make this only for them ?

It’s documented [here](https://github.com/delight-im/PHP-Auth#enabling-or-disabling-password-resets). Alternatively, you could modify the records of the admin users in the `users` table [directly](https://github.com/delight-im/PHP-Auth/blob/7b2ac9b1072c9b95365fa803db2ba28908ebce5e/Database/MySQL.sql#L17).

> said "using roles OR differet status flag" with status flag something I have in mind... but I prefer to listen from you :) What do you mean for differenciate BE/FE with different status Flag ?

Well, we have the [roles](https://github.com/delight-im/PHP-Auth#available-roles) and also the [status flags](https://github.com/delight-im/PHP-Auth#status-information) here. Both can be set on individual user records. You can use either of those to implement your access rights. Choose which one you prefer. Of course, you may even implement a custom concept using a custom database table and some application code.

> request from FE include routes_frontend.phpand request from BE routes_backend.php if yes what I am thinking to do is ?

You could load the routes conditionally, yes. But you could also load *all* routes every time, and just use two separate files `routes_frontend.php` and `routes_backend.php` (which you include in `index.php`) for better overview and a tidy definition of routes. After all, you can also include all routes in that single file, but it may end up becoming too long and too messy. Maybe you don’t want to bother with this immediately and just think about this again when it becomes an issue.

> for better manage backup, import and so on the better way should be include directly in the folder of the theme the css and js over than layout and template..

If you create folders like `backend` and `frontend` in your `views` directory, you can certainly create the same folders in `public` to put your `css` and `js` in. The `public` directory is served handled differently and served directly, so CSS and JS should really go there.

> Great to listen that you are rebuild I18N there is already some repositories that is possible to check or I can use it and update later ?

There’s nothing available yet, unfortunately. But you can definitely use the old I18N class first and later switch to something else. Switching won’t be much work, as the I18N class only sets up Gettext and the latter is what you really manage your translations with. Gettext is a widely supported standard tool and bundled with PHP.

**Comment by daebak74** [comment]
@ocram Thank you very much is time to write something. :) 
Anyway if you have time or already wrote something could be really great to check your concept of integration for BE/FE. :)
I leave open for future update but if you think to close it's ok.
Thanks.

**Comment by ocram** [comment]
I feel that the possible ways of having both a frontend (for end users) and a backend (for staff) have been explained.

You could have (1/3) two entirely separate applications, (2/3) one application where the `views`, the CSS files, JS files and images in `public` and the application logic and routes in `app` are separated in two folders, or (3/3) one application where everything is mixed together.

So that’s why I’m closing here. But please feel free to open a new issue if you have any specific questions.
