### ISSUE TITLE
gettext that lets translate PHP and Twig by App

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#30]
Hi,
I edited the post because it was not clear.

For large projects, having the ability to translate via the interface is more convenient and collaborative. 

I have seen that you can export files via command but I don't understand why running the command with shell_exec ('i18n.sh') it executes but it never ends and it doesn't extract anything from me. 

I was evaluating this library that import, export and edit by collecting several files. 

https://github.com/php-gettext/Gettext

Did you get to see it ? I'd like to know your opinion? I think making it point to the locale storage folder should work. I don't know if I might have difficulty with the rest of your library convention _ () {{_ ()}} but I think your library has already done the job before to store in locale files.

Any suggestion ?

Thanks.

**Comment by ocram** [comment]
Of course, using the supplied `i18n.sh` you can translate both directly in the text files or using a GUI by opening the generated files with your application of choice.

What OS are you using? Windows, macOS, Linux? The script `i18n.sh` is for Unix-based OSs.

The different function names, e.g. `_` and `_f`, should not be a problem. Virtually all Gettext utilities support this. The only problem is Gettext strings in templates. That’s why we have the utility for pre-generating the templates to make this work.

You can check what `i18n.sh` does and do the same on Windows, if that’s what you’re using.

If you’re on a Unix-based OS, please check if there are any error messages or warnings with that script.

**Comment by daebak74** [comment]
At the moment for convenience I use wamp server on windows but of course it must be destined for a vps. For this reason I wanted to solve via script.

Purge the cache and rebuild templates I run from gui and work good but I can't run shell script.

For this the Library GetText can solve my problem but I don't have enough experience with gettext I don't know if can work good with yours.

**Comment by ocram** [comment]
So yes, with Windows and a WAMP server, you can’t use the Shell script for Unix-based OSs.

Extracting the strings and generating the translations is usually done on the development machine, not on the server that will eventually run the application.

On Windows 10, you could perhaps look into the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10), install Gettext there and finally run the Shell script `i18n.sh`.

Otherwise, using other utilities, you would have to do something similar to `i18n.sh` yourself. What it does is get all PHP source files, ignore the `/vendor` directory, run Gettext on the PHP source files (specifying all the different keywords and methods with the correct formats and parameters), then putting the generated files into the correct destination folders, merging with existing translations, and compiling the binary files used by Gettext.

**Comment by daebak74** [comment]
Anyway for the framework wouldn't better to make a php extractor script more fast integration with a translation in GUI ?

Thanks I'll try my best to solve it :)

**Comment by ocram** [comment]
Well, you can already use everything with a GUI today. The specialized script is better at extracting the Gettext strings than a GUI could be, because it knows how this framework works. After that, when working with the extracted strings, translating them, perhaps even sending them to third-party translators, you can do all that with any GUI you like. This works together perfectly.

What you’re right about is that a PHP-based solution would be cross-platform while the current Shell script for Unix-based OSs is not.

But since the Shell script works great and you should be able to use them even on Windows (with the WSL, or otherwise in a VM), a PHP implementation has really low priority at the moment. Sorry!

**Comment by daebak74** [comment]
No, it's ok I installed WSL and seems fast and simple but I re-open because if I try 
`bash ./i18n.sh en-US `
give me this error

```
i18n.sh: line 2: $'\r': command not found
i18n.sh: line 6: $'\r': command not found
: invalid option set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
i18n.sh: line 8: $'\r': command not found
i18n.sh: line 10: cd: i18n.sh: Not a directory
: numeric argument required
```

**Comment by ocram** [comment]
Thanks for trying!

This looks like `\r\n` line endings instead of `\n`:

https://askubuntu.com/a/1046371

**Comment by ocram** [comment]
You may also have to run `sudo apt-get install gettext` inside WSL.

**Comment by daebak74** [comment]
Installed. 

```
 dpkg -s gettext
Package: gettext
Status: install ok installed
```
I run bash command from prompt but continue to give me the same problem. I think that I need to run from WSL. If yes I need to understand how to go to folder z:/wamp/www/phpfoundation :(

**Comment by daebak74** [comment]
Thanks. Everything works!

**Comment by daebak74** [comment]
Sorry but before to write any code for translate I would to understand if I got well.

I have this 2 files:

```
messages.po
messages.mo
```

If I want to translate from app I need to update the translation into msgstr "" than once completed I have to overwrite the messages.po file with the translated one and run the bash command again. Correct?

What I don't understand is the fuzzy part. Does this mean that if I change some string in the code and relaunch the bash command, a # will be added above the string in the po file? once translated will I have to delete this #?

Thanks.

**Comment by ocram** [comment]
Great to hear that it works with WSL, thanks a lot for trying!

You never touch the `*.mo` files manually. These are generated by `i18n.sh` and that’s it. They are what is actually being used by PHP, but they’re always auto-generated.

As for the `*.po` files, you generate them at first by extracting the strings. Then you edit those same files by filling in your translations. Finally, you just run the script again to convert these into the `*.mo` files.

And yes, `msgstr ""` entries are untranslated entries. So these are what you need to work on.

Fuzzy entries are generated when the original text has changed, but only slightly. So it is still assigned the old translation, but you cannot be sure that the translation is still correct. So they are marked and should be reviewed. When reviewed, remove the fuzzy mark.

Does that help?
