### ISSUE TITLE
Access session variable from template

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#6]
I don't know if there is some method for access Session variable {{ app.session}}. The helper available are that one present in your doc section Helper (templates). I think that I need to declare my function. it's Correct ?

For this I was thinking to make a controller and collect all my Helper as the follow:

```
public static function getGlobals(App $app) {
    return array(
        'session'   => $_SESSION,
    ) ;
}
```

so $_SESSION['my'] become {{session.my}} 
Is a correct way or there is something that I missed ? :)

- Some SESSION variable I use for change value according the url (route) just for a fast example if in controller class Login { $_SESSION ['PAGE_TITLE'] = -('login') I can use it in template <title></title>
there is a way to set or extend route definition some method add as symfony?

```
$routes = new RouteCollection();
$routes->add('blog', new Route('/blog/{page}', [
    '_controller' => 'App\Controller\BlogController::index',
    'page'        => 1,
    'title'       => 'Hello world!',
]));

return $routes;
```

- For enable other Twig function for example {{dump()}} or other I need to include a my config.php file into index.php ?

```
$twig = new Twig_Environment($loader, [
    'debug' => true,
    // ...
]);
$twig->addExtension(new Twig_Extension_Debug());
```

Thanks!

**Comment by ocram** [comment]
The README documents three ways of passing data or functions into templates.

The most common way is to pass data explicitly, which is what you’d usually want to do:

```php
echo $app->view('welcome.html.twig', [
    'userId' => $id
    'name' => $name
    'messages' => $messages
]);
```

Generally, you don’t want the templates to have full access to all data and all functions, because you want to avoid any application logic in the templates wherever possible. The controller should prepare everything and the template should just do one thing: display the data that is available.

The next way that is documented allows you to pass functions into (all) templates which you can then use as filters:

```php
// Twig: {{ myVariable | repeatAndReverse }}

$app->getTemplateManager()->addFilter('repeatAndReverse', function ($str) {
    return \strrev($str . ' ' . $str);
});
```

Finally, you can pass global variables into (all) templates like this, which might work for your session variables, if that’s necessary:

```php
// Twig: {{ session.myVariable }}

$app->getTemplateManager()->addGlobal('session', $_SESSION);
```

Does that help?

**Comment by daebak74** [comment]
I often forget the simplest solutions :)

```
echo $app->view('welcome.html.twig', [
    'userId' => $id
    'name' => $name
    'messages' => $messages
]);
```

Thanks!
