### ISSUE TITLE
I18N Class and Twig templates

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#7]
I decided to follow your suggestion to use the Old I18N Class but in Twig template I should to enable the extensions or there is some other solutions ?

Using {% trans %} I get Twig_Error_Syntax: Unknown "trans" tag.

`// $twig->addExtension(new Twig_Extensions_Extension_I18n());`

Thanks.

**Comment by ocram** [comment]
That `trans` tag requires a separate [Twig extension](https://github.com/twigphp/Twig-extensions). But I’m not sure you really need it. It can definitely be implemented without that:

 1. Update `delight-im/foundation-core` to `v4.1.0`:

    ```
    composer update delight-im/foundation-core
    ```

 1. In `/app/index.php`, add the following line at the top to make Gettext available in all templates:

    ```php
    $app->getTemplateManager()->addFunction('_', 'gettext');
    ```

 1. Use `{{ _('Hello world') }}` in your templates in `/views`

 1. Let `xgettext` or Poedit scan the two directories `/app` and `/storage/framework/views/cache` for translatable strings

Does that work for you? By the way, let’s track progress here for a direct integration of the I18N class and documentation of these features.

**Comment by daebak74** [comment]
Yes Work good!

Some question about multilang

- The folder so structured should to put in root ?

i18n/de_DE/LC_MESSAGES

- In view I saw inside folder mail templates in en, de (for example confirm-email.txt.twig) but in test file I didn't find any example How to set template for send email confirmation after registration ?

maybe something... 
`$app->mail()->loadTemplate('mail.twig');`

- For translation of text in JS code ?

Thanks.

**Comment by ocram** [comment]
Thanks, great to hear that it works.

The directory can be specified in the call to `I18N::init`, so you could even use something like `/internationalization/translations` if you prefer, but `/i18n` (in the root) is totally fine.

For the next two levels of the paths, something like `de_DE/LC_MESSAGES` is correct as well, yes.

How to translate phrases in JS files is an excellent question. JavaScript has no Gettext support. You may add a third-party solution like [this](https://messageformat.github.io/Jed/) if you like. What we do, however, is just use `data-my-key="..."` tags everywhere in HTML and fetch those from JavaScript (and jQuery). These tags do already contain localized phrases in HTML, as that’s easy to do from the views.

Regarding the email templates, these are indeed not integrated anywhere. That’s because it’s up to you how to implement email confirmation and any email delivery. Perhaps you prefer SwiftMailer, or PHPMailer, or just PHP’s `mail` function, or an external delivery service. The templates are just provided for convenience. Either use them or not.

**Comment by daebak74** [comment]
Thanks as usuall your reply are always helpfull. :)

About the folder I got it!

For j I didn't know the solution I'll check it by the way when you speak you add the data attribute data-my-key means that fetch the  already declared _() and don't need to traslate again ?

About the email yes I got it from the doc. It's correct to let select the library. I decided swiftMailer but render the View need to select assign template.

Excluding the part of mail library settings (subject, body and so on)... for select the template how ?

from twig doc 

```
$template = $twig->loadTemplate('mail.twig'); <- THIS PART

$parameters  = array(
    'customer' => $customer
);

$subject  = $template->renderBlock('subject',   $parameters);
$bodyHtml = $template->renderBlock('body_html', $parameters);
$bodyText = $template->renderBlock('body_text', $parameters);$twig = $this->get('twig'); // 
```

..... and so on

Thanks.

**Comment by ocram** [comment]
For JavaScript internationalization, we write

```html
<button data-success-message="{{ _('That worked!') }}">Some button</button>
```

in HTML and then just call

```javascript
var translatedMessage = $("button").data("success-message");
```

in JavaScript.

If you want to load a template, e.g. the mail templates, you don’t interact with Twig directly. For this framework, you only interact with Twig’s syntax in the template files. But from PHP code, you never call Twig. Just call

```php
$contents = $app->view('my_mail_template.txt.twig', [ 'myParam' => $myParam ]);
```

as you would do if you wanted to return an HTML template in a controller.

**Comment by ocram** [comment]
Full support for internationalization (I18N) and localization (L10N) is finally here. The [internationalization component](https://github.com/delight-im/PHP-I18N) has been completely rewritten and has also been integrated into this framework.

If you want to use the new component and integration, this is what you’d need to do in order to upgrade:

 1. Update the framework:

    ```bash
    $ composer update delight-im/router
    $ composer require delight-im/foundation-core "^4.8.1"
    ```

 1. Add some new configuration directives to `config/.env` (and probably also `config/.env.example`), as described [here](https://github.com/delight-im/PHP-Foundation/commit/fb8067b5ab58e123d05bdb32a1e2b5967045233b)

 1. Create `i18n.sh` as described [here](https://github.com/delight-im/PHP-Foundation/commit/fb8067b5ab58e123d05bdb32a1e2b5967045233b)

 1. Add a few lines to `index.php` as described [here](https://github.com/delight-im/PHP-Foundation/commit/fb8067b5ab58e123d05bdb32a1e2b5967045233b)

 1. Create a folder named `locale` with just a `.gitignore` inside, as described [here](https://github.com/delight-im/PHP-Foundation/commit/fb8067b5ab58e123d05bdb32a1e2b5967045233b)

 1. Find the documentation [here](https://github.com/delight-im/PHP-Foundation#internationalization-i18n-and-localization-l10n)

**Comment by daebak74** [comment]
Great.
